[package]
name = "unreal-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"

[dependencies.clap]
version = "4.4.18"
features = ["derive"]

[dependencies.nix]
version = "0.27.1"
default-features = false
features = ["user", "sched", "mount"]
