[package]
name = "wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
copy_dir = "0.1.3"
walkdir = "2.5.0"

[dependencies.clap]
version = "4.5.43"
features = ["derive"]

[dependencies.rustix]
version = "1.0.8"
features = ["process", "thread", "mount"]
